// Common
export const SHOW_LOADING = 'SHOW_LOADING';
export const OPEN_MODAL_FORM = 'OPEN_MODAL_FORM';

// Trucks
export const GET_TRUCK_TYPES = 'GET_TRUCK_TYPES';
export const GET_TRUCK_TYPES_SUCCESS = 'GET_TRUCK_TYPES_SUCCESS';